### ISSUE TITLE
Run without re-building doesn't load

### ISSUE THREAD

**Issue by zhiiiyang** [JEFworks-Lab/MERmaid#11]
Hi, thank you for making the tool. I was following the step of Run without re-building. However, the website http://localhost:8080/ doesn't load. Could you tell me if I did anything wrong? 

![image](https://user-images.githubusercontent.com/7269113/103249771-a5d8d280-4925-11eb-8258-a967d29adcb0.png)

**Comment by JEFworks** [comment]
This issue has been resolved in commit 0943877

For javascript debugging issues in the future, you can right click to view the web console (such as the one shown below). The console will help provide more information on what went wrong. The error was initially due to files not being found from an incorrect base url name. 
<img width="1030" alt="Screen Shot 2021-01-01 at 10 39 34 AM" src="https://user-images.githubusercontent.com/8975944/103441683-a9b66e80-4c1d-11eb-9212-68cf2316a7a6.png">

**Comment by zhiiiyang** [comment]
It works! Thank you so much.
